version: '3.9'
services:
  web:
    container_name: web
    hostname: web
    build: .
    command: bash -c "rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    tty: true
    depends_on:
      - "db"
  db:
    image: mariadb:10.5.8
    container_name: db
    hostname: db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
